PERSON_CLASS_ID = 0


# Analysis status
ANALYSIS_PENDING = "PENDING"
ANALYSIS_PROCESSING = "PROCESSING"
ANALYSIS_COMPLETED = "COMPLETED"
ANALYSIS_FAILED = "FAILED"


# Congestion levels
CONGESTION_NORMAL = "NORMAL"
CONGESTION_MODERATE = "MODERATE"
CONGESTION_HIGH = "HIGH"


# Risk levels
RISK_LOW = "LOW"
RISK_MEDIUM = "MEDIUM"
RISK_HIGH = "HIGH"


# Base-paper behaviour classes
BEHAVIOUR_WANDERING = "Wandering"
BEHAVIOUR_MERGING = "Merging"
BEHAVIOUR_STANDING_GATHERING = "Standing Gathering"
BEHAVIOUR_WALKING_GATHERING = "Walking Gathering"
BEHAVIOUR_DISPERSING = "Dispersing"


BEHAVIOUR_CLASSES = [
    BEHAVIOUR_WANDERING,
    BEHAVIOUR_MERGING,
    BEHAVIOUR_STANDING_GATHERING,
    BEHAVIOUR_WALKING_GATHERING,
    BEHAVIOUR_DISPERSING,
]